name: Self Test (Auggie Reusable)

on:
  workflow_dispatch:
    inputs:
      dry-run:
        description: 'Run without committing/pushing or opening PR; upload artifacts only'
        required: false
        default: 'true'

permissions:
  contents: write
  pull-requests: write

jobs:
  test:
    uses: rishitank/auggie-dependabot/.github/workflows/auggie.yml@main
    with:
      pr-labels: 'dependencies,auggie,self-test'
      pr-reviewers: ''
      auggie-config-path: '.auggie.yml'
      auggie-run-args: '--compact'
      dry-run: ${{ inputs.dry-run }}
    secrets: inherit

